
name: Upload Data - Cron

# on:
#  schedule:
#    - cron:  "0 11 * * *"
on: workflow_dispatch


jobs:
  upload-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest

        sudo apt-get update
        sudo apt-get install ffmpeg

        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Run - Upload Data
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/news_lk_si/pipeline.py

    - name: Checkout repo branch data
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp /tmp/news_lk_si.* .
        echo "* $(date)" >> update.log
        git add .
        git commit -m "Updated data $(date)"
        git push origin data
